# Generated by Django 5.1.6 on 2025-02-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detallefactura_created_at_producto_created_at_and_more'),
        ('recetas', '0002_detallereceta_created_at_receta_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='receta',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas.receta')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleReceta',
        ),
    ]
