# Generated by Django 5.1.6 on 2025-02-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detallefactura_created_at_producto_created_at_and_more'),
        ('recetas', '0003_remove_receta_created_at_remove_receta_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
